name: TempestBoss
version: 1.2.0
main: me.alec.tempestboss.TempestBossPlugin
api-version: "1.21"
author: Alec

commands:
  boss:
    description: Boss admin commands
    usage: /boss help
  bossgui:
    description: Open boss control panel GUI (admin)
    usage: /bossgui
    aliases: [bossmenu, bossui]
  bossspawn:
    description: Open spawn GUI (admin)
    usage: /bossspawn

permissions:
  tempestboss.admin:
    default: op
